### ISSUE TITLE
empty paramters from GLPIplugin to glpi-agent

### ISSUE THREAD

**Issue by plpamos** [glpi-project/glpi-inventory-plugin#388]
### Describe the bug

no iprange givent to glpi-agent - job (net ranges) properly defined for netdiscovery and netinventory also

[debug] [http client] Using Compress::Zlib for compression
[info] sending prolog request to server0
[debug2] [http client] sending message:
 <?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <DEVICEID>xxxx.yyyy.net-2020-08-27-23-27-13</DEVICEID>
  <QUERY>PROLOG</QUERY>
  <TOKEN>12345678</TOKEN>
</REQUEST>
[debug2] format: Zlib
[debug2] [http client] receiving message:

```
 <?xml version="1.0"?>
<REPLY><PROLOG_FREQ>24</PROLOG_FREQ><RESPONSE>SEND</RESPONSE><OPTION>
<NAME>NETDISCOVERY</NAME><PARAM THREADS_DISCOVERY="20" TIMEOUT="1" PID=""/><RANGEIP ID="" IPSTART="" IPEND="" ENTITY=""/></OPTION></REPLY>
```

[error] invalid range: no first address defined
[error] invalid job: no valid IP range defined
[error] no valid job found, aborting

### To reproduce

create and preapre job.
problem after upgrade from fusionventory to glpiinventory after uppgrade of GLPI to 10.0.9 - new version forced switching off fusioninventory plugin. Everything worked fine with glpiinventory 1.1, after upgrade to 1.2.3 ( incremental update of every version) such issue happend

### Expected behavior

rub defined job at agent-side

### Operating system

Linux

### GLPI Agent version

1.5

### GLPI version

10.0.9

### GLPIInventory plugin

1.2.3

### Additional context

glpiinventory ver. 1.2.3 glpi ver 10.0.9 OS Linux Debian 
glpi-agent v 1.5 OS Linux Debian buster

**Comment by plpamos** [comment]
this debug line  also can be ralated:
[2023-08-14 11:30:01] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 379
  *** MySQL query error:
  SQL: INSERT INTO `glpi_plugin_glpiinventory_taskjobstates` (`state`, `itemtype`, `items_id`, `plugin_glpiinventory_taskjobs_id`, `agents_id`, `uniqid`) VALUES ('0', 'PluginGlpiinventoryIPRange', '10', NULL, '2', '64d9f4196c75c')
  Error: Column 'plugin_glpiinventory_taskjobs_id' cannot be null
  Backtrace :
  src/DBmysql.php:1349
  src/CommonDBTM.php:722                             DBmysql->insert()
  src/CommonDBTM.php:1323                            CommonDBTM->addToDB()
  marketplace/glpiinventory/inc/task.class.php:822   CommonDBTM->add()
  marketplace/glpiinventory/inc/task.class.php:972   PluginGlpiinventoryTask->prepareTaskjobs()
  src/CronTask.php:1018                              PluginGlpiinventoryTask::cronTaskscheduler()
  front/cron.php:83                                  CronTask::launch()

**Comment by stonebuzz** [comment]
Hi @plpamos 

maybe #393 

can you try it ?

**Comment by plpamos** [comment]
doesnt fit :(..

[2023-08-21 09:14:22] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 379
  *** MySQL query error:
  SQL: INSERT INTO `glpi_plugin_glpiinventory_taskjoblogs` (`state`, `plugin_glpiinventory_taskjobstates_id`, `items_id`, `itemtype`, `date`, `comment`) VALUES ('4', NULL, NULL, NULL, '2023-08-21 09:14:22', 'Device have no ip')
  Error: Column 'plugin_glpiinventory_taskjobstates_id' cannot be null
  Backtrace :
  src/DBmysql.php:1349
  src/CommonDBTM.php:722                             DBmysql->insert()
  src/CommonDBTM.php:1323                            CommonDBTM->addToDB()
  ...ce/glpiinventory/inc/taskjobstate.class.php:399 CommonDBTM->add()
  ...lpiinventory/inc/networkinventory.class.php:582 PluginGlpiinventoryTaskjobstate->changeStatusFinish()
  ...e/glpiinventory/inc/communication.class.php:196 PluginGlpiinventoryNetworkinventory->run()
  marketplace/glpiinventory/hook.php:1061            PluginGlpiinventoryCommunication->getTaskAgent()
  src/Plugin.php:1702                                plugin_glpiinventory_prolog_response()
  src/Inventory/Request.php:216                      Plugin::doHookFunction()
  src/Inventory/Request.php:86                       Glpi\Inventory\Request->prolog()
  src/Agent/Communication/AbstractRequest.php:332    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:269    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()
  {"user":"@XXXXXX"}

-----

[debug2] [http client] 12259AA4: received message:
{"expiration":"24","status":"ok"}
[debug2] [http client] Using Compress::Zlib for compression
DEBUG: .../IO/Socket/SSL.pm:2875: free ctx 94040337293904 open=94040337293904
DEBUG: .../IO/Socket/SSL.pm:2879: free ctx 94040337293904 callback
DEBUG: .../IO/Socket/SSL.pm:2886: OK free ctx 94040337293904
[info] sending prolog request to server0
[debug2] [http client] sending message:
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <DEVICEID>XXXXXXX-2023-08-09-12-46-29</DEVICEID>
  <QUERY>PROLOG</QUERY>
  <TOKEN>ZZZZZZZ</TOKEN>
</REQUEST>
DEBUG: .../IO/Socket/SSL.pm:2853: new ctx 94040344165648
DEBUG: .../IO/Socket/SSL.pm:692: socket not yet connected
DEBUG: .../IO/Socket/SSL.pm:694: socket connected
DEBUG: .../IO/Socket/SSL.pm:717: ssl handshake not started
DEBUG: .../IO/Socket/SSL.pm:750: using SNI with hostname pldeb02.btworld.net
DEBUG: .../IO/Socket/SSL.pm:785: request OCSP stapling
DEBUG: .../IO/Socket/SSL.pm:806: set socket to non-blocking to enforce timeout=180
DEBUG: .../IO/Socket/SSL.pm:819: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:822: done Net::SSLeay::connect -> -1
DEBUG: .../IO/Socket/SSL.pm:832: ssl handshake in progress
DEBUG: .../IO/Socket/SSL.pm:842: waiting for fd to become ready: SSL wants a read first
DEBUG: .../IO/Socket/SSL.pm:862: socket ready, retrying connect
DEBUG: .../IO/Socket/SSL.pm:819: call Net::SSLeay::connect
DEBUG: .../IO/Socket/SSL.pm:2707: ok=1 [1] /CN=XXXXX/CN=XXXXX
DEBUG: .../IO/Socket/SSL.pm:2707: ok=1 [0] /CN=XXXX/C=PL/ST=XXXX [...cut...] 
DEBUG: .../IO/Socket/SSL.pm:1760: scheme=www cert=94040343422016
DEBUG: .../IO/Socket/SSL.pm:1770: identity=[... cut ..] 
DEBUG: .../IO/Socket/SSL.pm:2754: did not get stapled OCSP response
DEBUG: .../IO/Socket/SSL.pm:822: done Net::SSLeay::connect -> 1
DEBUG: .../IO/Socket/SSL.pm:877: ssl handshake done
[debug2] format: Zlib
[debug2] [http client] receiving message:
<?xml version="1.0"?>
<REPLY><PROLOG_FREQ>24</PROLOG_FREQ><RESPONSE>SEND</RESPONSE><OPTION><NAME>SNMPQUERY</NAME><PARAM/><DEVICE/></OPTION></REPLY>
DEBUG: .../IO/Socket/SSL.pm:2875: free ctx 94040344165648 open=94040344165648
DEBUG: .../IO/Socket/SSL.pm:2879: free ctx 94040344165648 callback
DEBUG: .../IO/Socket/SSL.pm:2886: OK free ctx 94040344165648
----

**Comment by stonebuzz** [comment]
are the IPRange in the same entity as the rest?

**Comment by plpamos** [comment]
> are the IPRange in the same entity as the rest?

yes, same. I've also tried different ranges, subnets max 1 hop, all in one physical segment.

**Comment by stonebuzz** [comment]
Can youvretry with 1.2.1 version, After we have refactoring all SQL queries (maybe its the problem)

**Comment by plpamos** [comment]
OK.. but should wait till monday :)

**Comment by plpamos** [comment]
@stonebuzz - works fine with 1.2.1 :)..

**Comment by stonebuzz** [comment]
Ok so we have a difference in the SQL queries to prepare and send the data to the agent.
I'll try to reproduce

**Comment by stonebuzz** [comment]
do you have SNMP communities attached to the IP range?

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/7335054/22fd9a22-b838-4805-b36f-74dfedacda58)

**Comment by plpamos** [comment]
@stonebuzz  - yes, all IP ranges got SNMP communities attached..
netdiscovery and netinventory are working fine with 1.2.1v , same parameters don't with 1.2.3v


in addtion - let's say "breaking point" just after downgrade last time observed Error: Column 'plugin_glpiinventory_taskjobs_id' cannot be null, and first  "error" related (I think)  to "gpliinventoryplugin activation - about duplicated entry. 

`
[2023-09-11 11:41:01] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 379
  *** MySQL query error:
  SQL: INSERT INTO `glpi_plugin_glpiinventory_taskjobstates` (`state`, `itemtype`, `items_id`, `plugin_glpiinventory_taskjobs_id`, `agents_id`, `uniqid`) VALUES ('0', 'PluginGlpiinventoryIPRange', '10', NULL, '2', '64fee0ade4575')
  Error: Column 'plugin_glpiinventory_taskjobs_id' cannot be null
  Backtrace :
  src/DBmysql.php:1349
  src/CommonDBTM.php:722                             DBmysql->insert()
  src/CommonDBTM.php:1323                            CommonDBTM->addToDB()
  marketplace/glpiinventory/inc/task.class.php:822   CommonDBTM->add()
  marketplace/glpiinventory/inc/task.class.php:972   PluginGlpiinventoryTask->prepareTaskjobs()
  src/CronTask.php:1018                              PluginGlpiinventoryTask::cronTaskscheduler()
  front/cron.php:83                                  CronTask::launch()
  {"user":"@xxxxxx.net","mem_usage":"0.001\", 24.02Mio)"}
[2023-09-11 11:46:06] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 379
  *** MySQL query error:
  SQL: UPDATE `glpi_crontasks` SET `itemtype` = REPLACE(`itemtype`, "PluginFusioninventory", "PluginGlpiinventory") WHERE `itemtype` LIKE 'PluginFusioninventory%'
  Error: Duplicate entry 'PluginGlpiinventoryAgentWakeup-wakeupAgents' for key 'glpi_crontasks.unicity'
  Backtrace :
  src/DBmysql.php:1468
  marketplace/glpiinventory/install/update.php:8728  DBmysql->update()
  marketplace/glpiinventory/install/update.php:367   renamePlugin()
  marketplace/glpiinventory/hook.php:409             pluginGlpiinventoryUpdate()
  src/Plugin.php:911                                 plugin_glpiinventory_install()
  :                                                  Plugin->install()
  src/Marketplace/Controller.php:545                 call_user_func()
  src/Marketplace/Controller.php:435                 Glpi\Marketplace\Controller->setPluginState()
  ajax/marketplace.php:82                            Glpi\Marketplace\Controller->installPlugin()
  {"user":"59@xxxxxxx.net"}
`

**Comment by stonebuzz** [comment]
it seems that a task uses an actor (Agent) that no longer exists 

> [2023-09-11 11:36:02] glpiphplog.WARNING: *** PHP User Warning (512): Invalid item "Agent" (1405). in

you can find this task with the following SQL query (column ```plugin_glpiinventory_tasks_id```)

```sql
SELECT * FROM  glpi_plugin_glpiinventory_taskjobs WHERE actors like "%1405%"
``` 

Can you fix ```actors``` and retry

**Comment by stonebuzz** [comment]
For first problem (empty IP range send to agent)

can you retry with ```develop``` ?

**Comment by plpamos** [comment]
Ok..
Will try Monday but very busy week is coming.. so let me a bit more of time
;)

pt., 22 wrz 2023, 09:20 użytkownik Stanislas ***@***.***>
napisał:

**Comment by plpamos** [comment]
@stonebuzz  - Can test it . Maybe I would like to get from you some additional information howto install it.
1 - GLPI plugin demands GLPI versio 10.0.10 - OK, ?I'vemade sime "adjustment" at setup.php
2 - after "instalation" no erros about update procedure but can't activate plugin using stndard tools - I wouldn't "force" of "manual" SQL ingeration.
So .. give me some hints howto install devel version .. :)

**Comment by stonebuzz** [comment]
Hi @plpamos you can 

1 - Use a test environment with GLPI 10.0.10 and your PRODUCTION database.
2 - Get the develop branch here  (git clone / git checkout develop / composer install )
3 - Update the plugin
4 - Test

**Comment by cedric-anne** [comment]
Hi,

Please try to upgrade to version 1.3.1. Issue may have been fixed.

**Comment by plpamos** [comment]
sorry for long silence from me..  just life :)..

issue still persisits, after upgrad to version 1.3.4 with GLPI 10.0.11  so decided to downgrade to 1.2.1 - latest "working" version :(

**Comment by stonebuzz** [comment]
Hi @plpamos 

no problem =)

I'm not sure how to help you, since I don't reproduce on my side.

The data in your GLPI / plugin must be at fault.

Perhaps you should consider taking out a subscription to benefit from professional support.
This would allow me (among other things) to take control of your instance for debugging purposes.

**Comment by trasher** [comment]
Since we cannot reproduce; and existing data is certainly faultly; I close.

Feel free to reopen if you can provide a use case reproducing issue on a fresh install.
