### ISSUE TITLE
The agent does not start the Collect task because of wrong agent_base_url

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/glpi-inventory-plugin#56]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

There is a problem with collecting data from the registry using the agent; after starting the task, the agent is in the prepared status, and its status does not change in the future.

https://github.com/glpi-project/glpi-inventory-plugin/issues/46

### To reproduce

A test active task was created with 24/7 execution, with the collection of the registry of the glpi agent branch, namely the path of the certificate location and the specified group of computers on which the task must be performed. Details in the screenshots below.

### Expected behavior

Getting data from the registry

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.0-beta

### GLPIInventory plugin or FusionInventory for GLPI plugin version

10.0.0-rc3

### Additional context

GLPI version master.16615cb.tar.gz 2.02.2022.
GLPI agent version 1.1-git1d9ab8e9
[agent_log.txt](https://github.com/glpi-project/glpi-agent/files/7992735/agent_log.txt)
[php-errors.log](https://github.com/glpi-project/glpi-agent/files/7992736/php-errors.log)
![3](https://user-images.githubusercontent.com/97535165/152302545-0c0daec6-43d2-487d-a98b-f433941e2026.png)
![1](https://user-images.githubusercontent.com/97535165/152302548-2b81463c-4401-4a96-966f-2910f01f6524.png)
![2](https://user-images.githubusercontent.com/97535165/152302551-aac62796-6c60-4c45-972f-d56092e9f71c.png)

**Comment by g-bougard** [comment]
Hi @Badkempachi 
I tested myself and indeed, the URL is not shown in the field, this is a bug we will fix. If you set an URL it is saved in database. If you save with the field empty it is saved empty in database.

So can you just "Save" to test if your Collect task works when `agent_base_url` is empty ?

**Comment by g-bougard** [comment]
The UI problem not showing Agent base URL should be fixed in GLPI by [Fix entity config display #10749](https://github.com/glpi-project/glpi/pull/10749).

**Comment by cedric-anne** [comment]
> Anyway I'll investigate why it can have been set in database to something with `/ajax/marketplace.php` at the end.

Fixed by #57 .

**Comment by Badkempachi** [comment]
> Hi @Badkempachi I tested myself and indeed, the URL is not shown in the field, this is a bug we will fix. If you set an URL it is saved in database. If you save with the field empty it is saved empty in database.
> 
> So can you just "Save" to test if your Collect task works when `agent_base_url` is empty ?

Hi @g-bougard 
On the test environment, I saved to the “Home->Administration->Entities->Assets” page with an empty string “ Agent base URL ” after that, in glpi, I could see the result of the task being executed by the agent. With glpi, which is used as the main one, this problem did not disappear on it, testing in both cases was carried out after updating the nightly build from 2022-02-24.

It can be seen in the agent logs that the problem that was previously with json decoding is missing, the agent successfully receives registry data and sends it to the server, but the strangest thing is that there are no errors in the logs on the glpi server, please help in solving the problem, since in my case reinstallation from scratch is not an option.


[Thu Feb 24 12:33:07 2022][debug] new thread 15 to handle task Deploy
[Thu Feb 24 12:33:07 2022][info] running task Deploy
[Thu Feb 24 12:33:07 2022][debug2] https://glpi.localhost.ru/marketplace/glpiinventory?action=getConfig&machineid=username.localhost.ru-2022-01-12-12-57-16&task[Deploy]=2.9
[Thu Feb 24 12:33:07 2022][info] No Deploy job enabled or Deploy support disabled server side.
[Thu Feb 24 12:33:07 2022][debug] new thread 16 to handle task Collect
[Thu Feb 24 12:33:07 2022][info] running task Collect
[Thu Feb 24 12:33:07 2022][debug2] https://glpi.localhost.ru/marketplace/glpiinventory?action=getConfig&machineid=username.localhost.ru-2022-01-12-12-57-16&task[Collect]=2.8
[Thu Feb 24 12:33:07 2022][debug2] http://glpi.localhost.ru/marketplace/glpiinventory/b/collect/?action=getJobs&machineid=username.localhost.ru-2022-01-12-12-57-16
[Thu Feb 24 12:33:07 2022][debug2] path mandatory value is present in job
[Thu Feb 24 12:33:07 2022][debug2] path mandatory value is present in job
[Thu Feb 24 12:33:07 2022][debug2] Starting a collect job...
[Thu Feb 24 12:33:07 2022][debug2] Collect job has uuid: 62175095eeb31
[Thu Feb 24 12:33:07 2022][debug] Looking for 'HKEY_LOCAL_MACHINE/SOFTWARE/GLPI-Agent/logfile' registry key...
[Thu Feb 24 12:33:07 2022][debug2] Found REG_SZ value: C:\Program Files\GLPI-Agent\logs\glpi-agent.log
[Thu Feb 24 12:33:07 2022][debug2] http://glpi.localhost.ru/marketplace/glpiinventory/b/collect/?action=setAnswer&uuid=62175095eeb31&method=POST
[Thu Feb 24 12:33:07 2022][debug2] [http client] POST: action=setAnswer&_sid=9&_cpt=1&logfile=C%3A%5CProgram%20Files%5CGLPI-Agent%5Clogs%5Cglpi-agent.log&_glpi_csrf_token=f6556a6b33a7cf04e042161cc462bddaf6d786147e09e5526afddf72dd4d7033&uuid=62175095eeb31
[Thu Feb 24 12:33:08 2022][error] [http client] Can't decode JSON content, starting with 
[Thu Feb 24 12:33:08 2022][debug2] Starting a collect job...
[Thu Feb 24 12:33:08 2022][debug2] Collect job has uuid: 62175095eeb31
[Thu Feb 24 12:33:08 2022][debug] Looking for 'HKEY_LOCAL_MACHINE/SOFTWARE/GLPI-Agent/httpd-port' registry key...
[Thu Feb 24 12:33:08 2022][debug2] Found REG_SZ value: 62354
[Thu Feb 24 12:33:08 2022][debug2] http://glpi.localhost.ru/marketplace/glpiinventory/b/collect/?action=setAnswer&uuid=62175095eeb31&method=POST
[Thu Feb 24 12:33:08 2022][debug2] [http client] POST: action=setAnswer&httpd-port=62354&_sid=10&_cpt=1&uuid=62175095eeb31
[Thu Feb 24 12:33:08 2022][error] [http client] Can't decode JSON content, starting with 
[Thu Feb 24 12:33:08 2022][debug2] http://glpi.localhost.ru/marketplace/glpiinventory/b/collect/?action=jobsDone&uuid=62175095eeb31
[Thu Feb 24 12:33:08 2022][debug] new thread 17 to handle task NetDiscovery
[Thu Feb 24 12:33:08 2022][debug] NetDiscovery task execution not requested
[Thu Feb 24 12:33:08 2022][debug] new thread 18 to handle task NetInventory
[Thu Feb 24 12:33:08 2022][debug] NetInventory task execution not requested
[Thu Feb 24 12:33:09 2022][debug] new thread 19 to handle task ESX
[Thu Feb 24 12:33:09 2022][info] running task ESX
[Thu Feb 24 12:33:09 2022][debug2] https://glpi.localhost.ru/marketplace/glpiinventory?action=getConfig&machineid=username.localhost.ru-2022-01-12-12-57-16&task[ESX]=2.7
[Thu Feb 24 12:33:09 2022][info] No ESX job enabled or ESX support disabled server side.
[Thu Feb 24 12:33:09 2022][debug] new thread 20 to handle task RemoteInventory
[Thu Feb 24 12:33:09 2022][debug] Remote inventory task execution disabled: no remote set
[Thu Feb 24 12:33:10 2022][debug] new thread 21 to handle task Inventory
[Thu Feb 24 12:33:10 2022][info] running task Inventory

**Comment by g-bougard** [comment]
You still have a `Can't decode JSON content` error on the value submission:
```
[Thu Feb 24 12:33:07 2022][debug2] https://glpi.localhost.ru/marketplace/glpiinventory?action=getConfig&machineid=username.localhost.ru-2022-01-12-12-57-16&task[Collect]=2.8
[Thu Feb 24 12:33:07 2022][debug2] http://glpi.localhost.ru/marketplace/glpiinventory/b/collect/?action=getJobs&machineid=username.localhost.ru-2022-01-12-12-57-16
[Thu Feb 24 12:33:07 2022][debug2] path mandatory value is present in job
[Thu Feb 24 12:33:07 2022][debug2] path mandatory value is present in job
[Thu Feb 24 12:33:07 2022][debug2] Starting a collect job...
[Thu Feb 24 12:33:07 2022][debug2] Collect job has uuid: 62175095eeb31
[Thu Feb 24 12:33:07 2022][debug] Looking for 'HKEY_LOCAL_MACHINE/SOFTWARE/GLPI-Agent/logfile' registry key...
[Thu Feb 24 12:33:07 2022][debug2] Found REG_SZ value: C:\Program Files\GLPI-Agent\logs\glpi-agent.log
[Thu Feb 24 12:33:07 2022][debug2] http://glpi.localhost.ru/marketplace/glpiinventory/b/collect/?action=setAnswer&uuid=62175095eeb31&method=POST
[Thu Feb 24 12:33:07 2022][debug2] [http client] POST: action=setAnswer&_sid=9&_cpt=1&logfile=C%3A%5CProgram%20Files%5CGLPI-Agent%5Clogs%5Cglpi-agent.log&_glpi_csrf_token=f6556a6b33a7cf04e042161cc462bddaf6d786147e09e5526afddf72dd4d7033&uuid=62175095eeb31
[Thu Feb 24 12:33:08 2022][error] [http client] Can't decode JSON content, starting with
```

I see another little problem here but this is probably not the source of your problem: there's a switch from "https" url to "http" (not ssl) one. This means the address in agent `server` config uses "https", but the address in "agent_base_url" is using "http". You should fix this to be coherent.

My guess is the server returns an empty answer but I don't see why. Can you show us your apache server access_log with the related request handling ? As I said, without error in glpi log, you should find something useful somewhere in your Apache logs or in your php-fpm ones.

**Comment by Badkempachi** [comment]
Hey, @g-bougard 
I am attaching the logs
[logs.txt](https://github.com/glpi-project/glpi-inventory-plugin/files/8151393/logs.txt)
.

**Comment by Badkempachi** [comment]
> You still have a `Can't decode JSON content` error on the value submission:
> 
> ```
> [Thu Feb 24 12:33:07 2022][debug2] https://glpi.localhost.ru/marketplace/glpiinventory?action=getConfig&machineid=username.localhost.ru-2022-01-12-12-57-16&task[Collect]=2.8
> [Thu Feb 24 12:33:07 2022][debug2] http://glpi.localhost.ru/marketplace/glpiinventory/b/collect/?action=getJobs&machineid=username.localhost.ru-2022-01-12-12-57-16
> [Thu Feb 24 12:33:07 2022][debug2] path mandatory value is present in job
> [Thu Feb 24 12:33:07 2022][debug2] path mandatory value is present in job
> [Thu Feb 24 12:33:07 2022][debug2] Starting a collect job...
> [Thu Feb 24 12:33:07 2022][debug2] Collect job has uuid: 62175095eeb31
> [Thu Feb 24 12:33:07 2022][debug] Looking for 'HKEY_LOCAL_MACHINE/SOFTWARE/GLPI-Agent/logfile' registry key...
> [Thu Feb 24 12:33:07 2022][debug2] Found REG_SZ value: C:\Program Files\GLPI-Agent\logs\glpi-agent.log
> [Thu Feb 24 12:33:07 2022][debug2] http://glpi.localhost.ru/marketplace/glpiinventory/b/collect/?action=setAnswer&uuid=62175095eeb31&method=POST
> [Thu Feb 24 12:33:07 2022][debug2] [http client] POST: action=setAnswer&_sid=9&_cpt=1&logfile=C%3A%5CProgram%20Files%5CGLPI-Agent%5Clogs%5Cglpi-agent.log&_glpi_csrf_token=f6556a6b33a7cf04e042161cc462bddaf6d786147e09e5526afddf72dd4d7033&uuid=62175095eeb31
> [Thu Feb 24 12:33:08 2022][error] [http client] Can't decode JSON content, starting with
> ```
> 
> I see another little problem here but this is probably not the source of your problem: there's a switch from "https" url to "http" (not ssl) one. This means the address in agent `server` config uses "https", but the address in "agent_base_url" is using "http". You should fix this to be coherent.
> 
> My guess is the server returns an empty answer but I don't see why. Can you show us your apache server access_log with the related request handling ? As I said, without error in glpi log, you should find something useful somewhere in your Apache logs or in your php-fpm ones.

Hey, @g-bougard
I am attaching the logs
[logs.txt](https://github.com/glpi-project/glpi-inventory-plugin/files/8151393/logs.txt)

**Comment by g-bougard** [comment]
Hi @Badkempachi 

you should set server url on agent "server" parameter and in "agent_base_url" on server-side to exactly `https://glpi.localhost.ru/marketplace/glpiinventory/` to avoid 301 redirection, but I don't think this has any concern with the problem.

Anyway on the last request when the Collect answer is sent it seems the server is returning a really big answer:
```
**.*.42.15 - - [24/Feb/2022:12:33:08 +0300] "POST //marketplace/glpiinventory/b/collect/?action=setAnswer&uuid=62175095eeb31&method=POST HTTP/1.1" 200 34207 "http://glpi.localhost.ru/marketplace/glpiinventory/b/collect/" "GLPI-Agent_v1.2-git70294ae7"
```
The answer has 34207 bytes ! This is probably an HTML answer which means the expected code is probably not run for some reason. As the agent is not showing the content, this does not help us to understand what's happen. But you may have something in you apache configuration or php-fpm which make troubles.

Can you apply the following patch on your agent ? It will dump the full content answer at debug level after the "Can't decode JSON content" error:
```
diff --git a/lib/GLPI/Agent/HTTP/Client/Fusion.pm b/lib/GLPI/Agent/HTTP/Client/Fusion.pm
index 5d11ca9b6..8d843cae4 100644
--- a/lib/GLPI/Agent/HTTP/Client/Fusion.pm
+++ b/lib/GLPI/Agent/HTTP/Client/Fusion.pm
@@ -125,6 +125,7 @@ sub send { ## no critic (ProhibitBuiltinHomonyms)
         $self->{logger}->error(
             $log_prefix . "Can't decode JSON content, starting with $lines[0]"
         ) if $self->{logger};
+        $self->{logger}->debug("Answer content:\n$content\n----");
         return;
     }
 
```
Then can you retry a Collect task an share that received content ?

**Comment by Badkempachi** [comment]
> Hi @Badkempachi
> 
> you should set server url on agent "server" parameter and in "agent_base_url" on server-side to exactly `https://glpi.localhost.ru/marketplace/glpiinventory/` to avoid 301 redirection, but I don't think this has any concern with the problem.
> 
> Anyway on the last request when the Collect answer is sent it seems the server is returning a really big answer:
> 
> ```
> **.*.42.15 - - [24/Feb/2022:12:33:08 +0300] "POST //marketplace/glpiinventory/b/collect/?action=setAnswer&uuid=62175095eeb31&method=POST HTTP/1.1" 200 34207 "http://glpi.localhost.ru/marketplace/glpiinventory/b/collect/" "GLPI-Agent_v1.2-git70294ae7"
> ```
> 
> The answer has 34207 bytes ! This is probably an HTML answer which means the expected code is probably not run for some reason. As the agent is not showing the content, this does not help us to understand what's happen. But you may have something in you apache configuration or php-fpm which make troubles.
> 
> Can you apply the following patch on your agent ? It will dump the full content answer at debug level after the "Can't decode JSON content" error:
> 
> ```
> diff --git a/lib/GLPI/Agent/HTTP/Client/Fusion.pm b/lib/GLPI/Agent/HTTP/Client/Fusion.pm
> index 5d11ca9b6..8d843cae4 100644
> --- a/lib/GLPI/Agent/HTTP/Client/Fusion.pm
> +++ b/lib/GLPI/Agent/HTTP/Client/Fusion.pm
> @@ -125,6 +125,7 @@ sub send { ## no critic (ProhibitBuiltinHomonyms)
>          $self->{logger}->error(
>              $log_prefix . "Can't decode JSON content, starting with $lines[0]"
>          ) if $self->{logger};
> +        $self->{logger}->debug("Answer content:\n$content\n----");
>          return;
>      }
>  
> ```
> 
> Then can you retry a Collect task an share that received content ?

Hi, @g-bougard 
I set the "agent_base_url" parameter as you wrote earlier and it worked, now I can view the collected data from the agent in glpi. Thanks :)
